spring.application.name=exercice-3
server.port=8083

# Kafka Configuration
spring.kafka.streams.bootstrap-servers=localhost:9092
spring.kafka.streams.application-id=vehicle-monitoring-app

# Logging Configuration
logging.level.ma.enset=DEBUG
logging.level.org.apache.kafka=INFO
